### ISSUE TITLE
Put an "Are you sure?" on the Get People button

### ISSUE THREAD

**Issue by rapPayne** [rapPayne/edp-people-picker#1]
If the user hits "Get People", it resets everything. It's bad if they accidentally hit it.

On the button click, bring up a <dialog> that says something like "This will erase your current progress and reset everything. Are you sure?" If the user answers Yes, continue. Otherwise, do nothing.

**Comment by jaredrkozar** [comment]
I’ll work on this, feel free to assign it to me and I’ll work on it later today
